# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAiCommit < Formula
  desc "Generate Git commit messages from staged diffs using your preferred LLM CLI."
  homepage "https://github.com/takai/git-ai-commit"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/takai/git-ai-commit/releases/download/v0.4.1/git-ai-commit_0.4.1_darwin_amd64.zip"
      sha256 "13171e88a447eed26945e7572651ab71e31ca158f82031e190d28c6e0e3cb6eb"

      def install
        bin.install "git-ai-commit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/takai/git-ai-commit/releases/download/v0.4.1/git-ai-commit_0.4.1_darwin_arm64.zip"
      sha256 "26d9d3504b0f00349424ee995b3d8a8785e838ee0bd617dd592998df5dd69724"

      def install
        bin.install "git-ai-commit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/takai/git-ai-commit/releases/download/v0.4.1/git-ai-commit_0.4.1_linux_amd64.tar.gz"
      sha256 "6725465aec0fed9933677a2402ae459f9f6c8a50b92bd0792c2558006da25be8"
      def install
        bin.install "git-ai-commit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/takai/git-ai-commit/releases/download/v0.4.1/git-ai-commit_0.4.1_linux_arm64.tar.gz"
      sha256 "f61d1cff0f5876c10b9ca51c1c884f5cbed2a9cb35f7f9ee2835cbc5c6bd8313"
      def install
        bin.install "git-ai-commit"
      end
    end
  end
end
