# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAiCommit < Formula
  desc "Generate Git commit messages from staged diffs using your preferred LLM CLI."
  homepage "https://github.com/takai/git-ai-commit"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/takai/git-ai-commit/releases/download/v0.3.1/git-ai-commit_0.3.1_darwin_amd64.zip"
      sha256 "9d98c36769187ac82dd4a3041e84d33a3eea2969afec6bebc4595006d3bfb8ed"

      def install
        bin.install "git-ai-commit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/takai/git-ai-commit/releases/download/v0.3.1/git-ai-commit_0.3.1_darwin_arm64.zip"
      sha256 "a9d8c1b98daabd9c2e948d7ff4af7d9063313e83a3f46c93ffc30c26d0149fa9"

      def install
        bin.install "git-ai-commit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/takai/git-ai-commit/releases/download/v0.3.1/git-ai-commit_0.3.1_linux_amd64.tar.gz"
      sha256 "8ebca6cb74425bb404cf98672f2816f105b93449ae6e29bc440ba4dc9a40890f"
      def install
        bin.install "git-ai-commit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/takai/git-ai-commit/releases/download/v0.3.1/git-ai-commit_0.3.1_linux_arm64.tar.gz"
      sha256 "239fa1c9535619bf05f2ea5afde52802d1282161c14e1ac763b1be1cbd95452a"
      def install
        bin.install "git-ai-commit"
      end
    end
  end
end
