# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAiCommit < Formula
  desc "Generate Git commit messages from staged diffs using your preferred LLM CLI."
  homepage "https://github.com/takai/git-ai-commit"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/takai/git-ai-commit/releases/download/v0.7.1/git-ai-commit_0.7.1_darwin_amd64.zip"
      sha256 "0a12f1cde70ea58ff6cd06e6e192708a6b8d822d578f7a45a4aa5bbd9fbd3675"

      define_method(:install) do
        bin.install "git-ai-commit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/takai/git-ai-commit/releases/download/v0.7.1/git-ai-commit_0.7.1_darwin_arm64.zip"
      sha256 "0f1935ea21b221c43afb8d1370fe1fc4c0437c8fc6d56f23569b9ebdf43551d7"

      define_method(:install) do
        bin.install "git-ai-commit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/takai/git-ai-commit/releases/download/v0.7.1/git-ai-commit_0.7.1_linux_amd64.tar.gz"
      sha256 "a20c82dee7ced8bd192e7d4566b3c25ac5ad1f75dfdbb03094300628d817e11a"
      define_method(:install) do
        bin.install "git-ai-commit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/takai/git-ai-commit/releases/download/v0.7.1/git-ai-commit_0.7.1_linux_arm64.tar.gz"
      sha256 "a04f13cdb0cb4218cf55eb728178520124c545b538889623827dc14277c7650d"
      define_method(:install) do
        bin.install "git-ai-commit"
      end
    end
  end
end
